#!/bin/bash

if [[ "$EUID" -eq 0 ]]; then
  echo "Ceci installera la configuration clavier CA-FR globalement."
  echo "Pour installer pour votre usager seulement, utiliser ./install sans sudo"
  read -rp "Appyer sur Enter pour continuer, ou ^C pour interrompre"
  cd "$( dirname "${BASH_SOURCE[0]}" )"
  cp cf.{icns,keylayout} /Library/Keyboard\ Layouts
  touch /Library/Keyboard\ Layouts
  echo "Clavier Canadien Français installé dans /Library/Keyboard\ Layouts"
  echo "(Voir section Autre/Other; fermer la session ou redémarrer au besoin)"
else
  echo "Ceci installera la configuration clavier CA-FR pour $USER seulement."
  echo "Pour installer globalement, utiliser plutôt:"
  echo "% sudo ./install global"
  read -rp "Appyer sur Enter pour continuer, ou ^C pour interrompre"
  cd "$( dirname "${BASH_SOURCE[0]}" )"
  cp cf.{icns,keylayout} ~/Library/Keyboard\ Layouts
  touch ~/Library/Keyboard\ Layouts
  echo "Clavier Canadien Français installé dans $HOME/Library/Keyboard\ Layouts"
fi

open /System/Library/PreferencePanes/Keyboard.prefPane
